#!/bin/sh
autoload -Uz vcs_info
autoload -U colors && colors

precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git*+setmessage:*' hooks git-untracked

+vi-git-untracked(){
  if [[$(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
    git status --porcelain | grep '??' &> /dev/null ; then
  hook_com[staged]+='!'
fi
}

zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[green]%}%{$fg[red]%} %b%{$fg[blue]%})"
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[red]%} %b%{$fg[blue]%})%{$reset_color%}"
# PROMPT='%F{red}%/%f  $fg[blue]%}'
PROMPT="%B%{$fg[yellow]%}⚡% %(?:%{$fg_bold[green]%} :%{$fg_bold[red]%} )%{$fg[cyan]%}%c%{$reset_color%}"
PROMPT+="\$vcs_info_msg_0_ "
